name: gen_res
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 1.0.0
homepage: https://github.com/nguyenvantuyen98/gen_res
repository: https://github.com/nguyenvantuyen98/gen_res
documentation: https://github.com/nguyenvantuyen98/gen_res

environment:
  sdk: '>=3.2.1 <4.0.0'

version_gen:
  path: lib/src/utils/

dependencies:
  build: ^3.0.0
  path: ^1.8.0
  yaml: ^3.0.0
  mime: '>=1.0.0 <3.0.0'
  xml: ^6.0.0
  dartx: ^1.0.0
  color: ^3.0.0
  collection: ^1.15.0
  dart_style: ^3.0.0
  analyzer:
  args: ^2.0.0
  pub_semver: ^2.0.0
  source_span: ^1.0.0
  json_annotation: ^4.4.0

dev_dependencies:
  lints: any
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  version_gen:
    git:
      url: https://github.com/bf-tuyennv/version_gen
      ref: main
